/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Administrador
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        box1_1 = new javax.swing.JTextField();
        box1_2_2_2 = new javax.swing.JTextField();
        box1_3 = new javax.swing.JTextField();
        box1_4 = new javax.swing.JTextField();
        box1_5 = new javax.swing.JTextField();
        box1_6_3_1 = new javax.swing.JTextField();
        box2_1 = new javax.swing.JTextField();
        box2_3 = new javax.swing.JTextField();
        box2_5 = new javax.swing.JTextField();
        box2_4 = new javax.swing.JTextField();
        box3_2 = new javax.swing.JTextField();
        box3_3 = new javax.swing.JTextField();
        box3_4 = new javax.swing.JTextField();
        box3_5 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        box4_6_6_2 = new javax.swing.JTextField();
        box4_5 = new javax.swing.JTextField();
        box4_4 = new javax.swing.JTextField();
        box4_3 = new javax.swing.JTextField();
        box4_2 = new javax.swing.JTextField();
        box4_1 = new javax.swing.JTextField();
        box4_7 = new javax.swing.JTextField();
        box6_1 = new javax.swing.JTextField();
        box6_4 = new javax.swing.JTextField();
        box6_3 = new javax.swing.JTextField();
        box6_5 = new javax.swing.JTextField();
        box3_11_6_6 = new javax.swing.JTextField();
        box6_7 = new javax.swing.JTextField();
        box5_4_6_8 = new javax.swing.JTextField();
        box3_10 = new javax.swing.JTextField();
        box3_8 = new javax.swing.JTextField();
        box3_9 = new javax.swing.JTextField();
        box3_6 = new javax.swing.JTextField();
        box3_7 = new javax.swing.JTextField();
        box5_5 = new javax.swing.JTextField();
        box5_3 = new javax.swing.JTextField();
        box5_2 = new javax.swing.JTextField();
        box5_1 = new javax.swing.JTextField();
        box7_5 = new javax.swing.JTextField();
        box7_4 = new javax.swing.JTextField();
        box7_1 = new javax.swing.JTextField();
        box7_2 = new javax.swing.JTextField();
        box5_7_7_3 = new javax.swing.JTextField();
        box5_10 = new javax.swing.JTextField();
        box5_8 = new javax.swing.JTextField();
        box5_6 = new javax.swing.JTextField();
        box5_9 = new javax.swing.JTextField();
        box7_9 = new javax.swing.JTextField();
        box7_8 = new javax.swing.JTextField();
        box7_7 = new javax.swing.JTextField();
        box7_6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPista = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnComprobarPalabra = new javax.swing.JButton();
        btnComprobarCrucigrama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        btn1.setText("1");
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setName(""); // NOI18N

        btn2.setText("2");
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn3.setText("3");
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("6");
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn5.setText("5");
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn6.setText("4");
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        box1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1_1ActionPerformed(evt);
            }
        });

        box1_2_2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1_2_2_2ActionPerformed(evt);
            }
        });

        box1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1_3ActionPerformed(evt);
            }
        });

        box1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1_4ActionPerformed(evt);
            }
        });

        box1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1_5ActionPerformed(evt);
            }
        });

        box1_6_3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1_6_3_1ActionPerformed(evt);
            }
        });

        box2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2_1ActionPerformed(evt);
            }
        });

        box2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2_3ActionPerformed(evt);
            }
        });

        box2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2_5ActionPerformed(evt);
            }
        });

        box2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2_4ActionPerformed(evt);
            }
        });

        box3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_2ActionPerformed(evt);
            }
        });

        box3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_3ActionPerformed(evt);
            }
        });

        box3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_4ActionPerformed(evt);
            }
        });

        box3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_5ActionPerformed(evt);
            }
        });

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        box4_6_6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4_6_6_2ActionPerformed(evt);
            }
        });

        box4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4_5ActionPerformed(evt);
            }
        });

        box4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4_4ActionPerformed(evt);
            }
        });

        box4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4_3ActionPerformed(evt);
            }
        });

        box4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4_2ActionPerformed(evt);
            }
        });

        box4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4_1ActionPerformed(evt);
            }
        });

        box4_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4_7ActionPerformed(evt);
            }
        });

        box6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6_1ActionPerformed(evt);
            }
        });

        box6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6_4ActionPerformed(evt);
            }
        });

        box6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6_3ActionPerformed(evt);
            }
        });

        box6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6_5ActionPerformed(evt);
            }
        });

        box3_11_6_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_11_6_6ActionPerformed(evt);
            }
        });

        box6_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6_7ActionPerformed(evt);
            }
        });

        box5_4_6_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_4_6_8ActionPerformed(evt);
            }
        });

        box3_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_10ActionPerformed(evt);
            }
        });

        box3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_8ActionPerformed(evt);
            }
        });

        box3_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_9ActionPerformed(evt);
            }
        });

        box3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_6ActionPerformed(evt);
            }
        });

        box3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3_7ActionPerformed(evt);
            }
        });

        box5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_5ActionPerformed(evt);
            }
        });

        box5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_3ActionPerformed(evt);
            }
        });

        box5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_2ActionPerformed(evt);
            }
        });

        box5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_1ActionPerformed(evt);
            }
        });

        box7_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_5ActionPerformed(evt);
            }
        });

        box7_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_4ActionPerformed(evt);
            }
        });

        box7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_1ActionPerformed(evt);
            }
        });

        box7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_2ActionPerformed(evt);
            }
        });

        box5_7_7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_7_7_3ActionPerformed(evt);
            }
        });

        box5_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_10ActionPerformed(evt);
            }
        });

        box5_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_8ActionPerformed(evt);
            }
        });

        box5_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_6ActionPerformed(evt);
            }
        });

        box5_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5_9ActionPerformed(evt);
            }
        });

        box7_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_9ActionPerformed(evt);
            }
        });

        box7_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_8ActionPerformed(evt);
            }
        });

        box7_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_7ActionPerformed(evt);
            }
        });

        box7_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn1)
                                    .addComponent(box2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(box1_2_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(box4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(box1_6_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(box1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(box3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(box3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(box3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(box3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(box1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn6))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(box1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(box1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(144, 144, 144)
                                                        .addComponent(box3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(box3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(box3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box3_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box3_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn5)
                                .addGap(136, 136, 136))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(box5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(box4_6_6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(box6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box3_11_6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(box5_4_6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(box6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(box5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(box5_7_7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box5_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(box7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box7_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(box6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(box1_2_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(box1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(box1_6_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(92, 92, 92))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(box6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(box4_6_6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(box4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(box4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(box4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(box4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(box4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(box4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(box6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(box6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(box6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(box3_11_6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(box3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(box5_4_6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(box7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(box7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(box5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box5_7_7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box7_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box7_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box7_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box7_8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(box7_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        textPista.setEditable(false);
        textPista.setColumns(20);
        textPista.setRows(5);
        textPista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(textPista);

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pistas >>>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        btnComprobarPalabra.setText("Comprobar Palabra Actual");
        btnComprobarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarPalabraActionPerformed(evt);
            }
        });

        btnComprobarCrucigrama.setText("Comprobar Crucigrama");
        btnComprobarCrucigrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarCrucigramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprobarCrucigrama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComprobarPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnComprobarPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprobarCrucigrama, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnComprobarCrucigramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarCrucigramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprobarCrucigramaActionPerformed

    private void btnComprobarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprobarPalabraActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void box1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1_1ActionPerformed

    private void box1_2_2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1_2_2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1_2_2_2ActionPerformed

    private void box1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1_3ActionPerformed

    private void box1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1_4ActionPerformed

    private void box1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1_5ActionPerformed

    private void box1_6_3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1_6_3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box1_6_3_1ActionPerformed

    private void box2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box2_1ActionPerformed

    private void box2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box2_3ActionPerformed

    private void box2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box2_5ActionPerformed

    private void box2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box2_4ActionPerformed

    private void box3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_2ActionPerformed

    private void box3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_3ActionPerformed

    private void box3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_4ActionPerformed

    private void box3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_5ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void box4_6_6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4_6_6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box4_6_6_2ActionPerformed

    private void box4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box4_5ActionPerformed

    private void box4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box4_4ActionPerformed

    private void box4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box4_3ActionPerformed

    private void box4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box4_2ActionPerformed

    private void box4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box4_1ActionPerformed

    private void box4_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box4_7ActionPerformed

    private void box6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box6_1ActionPerformed

    private void box6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box6_4ActionPerformed

    private void box6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box6_3ActionPerformed

    private void box6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box6_5ActionPerformed

    private void box3_11_6_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_11_6_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_11_6_6ActionPerformed

    private void box6_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box6_7ActionPerformed

    private void box5_4_6_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_4_6_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_4_6_8ActionPerformed

    private void box3_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_10ActionPerformed

    private void box3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_8ActionPerformed

    private void box3_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_9ActionPerformed

    private void box3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_6ActionPerformed

    private void box3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box3_7ActionPerformed

    private void box5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_5ActionPerformed

    private void box5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_3ActionPerformed

    private void box5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_2ActionPerformed

    private void box5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_1ActionPerformed

    private void box7_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_5ActionPerformed

    private void box7_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_4ActionPerformed

    private void box7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_1ActionPerformed

    private void box7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_2ActionPerformed

    private void box5_7_7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_7_7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_7_7_3ActionPerformed

    private void box5_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_10ActionPerformed

    private void box5_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_8ActionPerformed

    private void box5_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_6ActionPerformed

    private void box5_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box5_9ActionPerformed

    private void box7_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_9ActionPerformed

    private void box7_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_8ActionPerformed

    private void box7_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_7ActionPerformed

    private void box7_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box7_6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField box1_1;
    public javax.swing.JTextField box1_2_2_2;
    public javax.swing.JTextField box1_3;
    public javax.swing.JTextField box1_4;
    public javax.swing.JTextField box1_5;
    public javax.swing.JTextField box1_6_3_1;
    public javax.swing.JTextField box2_1;
    public javax.swing.JTextField box2_3;
    public javax.swing.JTextField box2_4;
    public javax.swing.JTextField box2_5;
    public javax.swing.JTextField box3_10;
    public javax.swing.JTextField box3_11_6_6;
    public javax.swing.JTextField box3_2;
    public javax.swing.JTextField box3_3;
    public javax.swing.JTextField box3_4;
    public javax.swing.JTextField box3_5;
    public javax.swing.JTextField box3_6;
    public javax.swing.JTextField box3_7;
    public javax.swing.JTextField box3_8;
    public javax.swing.JTextField box3_9;
    public javax.swing.JTextField box4_1;
    public javax.swing.JTextField box4_2;
    public javax.swing.JTextField box4_3;
    public javax.swing.JTextField box4_4;
    public javax.swing.JTextField box4_5;
    public javax.swing.JTextField box4_6_6_2;
    public javax.swing.JTextField box4_7;
    public javax.swing.JTextField box5_1;
    public javax.swing.JTextField box5_10;
    public javax.swing.JTextField box5_2;
    public javax.swing.JTextField box5_3;
    public javax.swing.JTextField box5_4_6_8;
    public javax.swing.JTextField box5_5;
    public javax.swing.JTextField box5_6;
    public javax.swing.JTextField box5_7_7_3;
    public javax.swing.JTextField box5_8;
    public javax.swing.JTextField box5_9;
    public javax.swing.JTextField box6_1;
    public javax.swing.JTextField box6_3;
    public javax.swing.JTextField box6_4;
    public javax.swing.JTextField box6_5;
    public javax.swing.JTextField box6_7;
    public javax.swing.JTextField box7_1;
    public javax.swing.JTextField box7_2;
    public javax.swing.JTextField box7_4;
    public javax.swing.JTextField box7_5;
    public javax.swing.JTextField box7_6;
    public javax.swing.JTextField box7_7;
    public javax.swing.JTextField box7_8;
    public javax.swing.JTextField box7_9;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btnComprobarCrucigrama;
    public javax.swing.JButton btnComprobarPalabra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField15;
    public javax.swing.JTextArea textPista;
    // End of variables declaration//GEN-END:variables
}
